[run]
dataset = "simulation"

[parameters]
latent_dim = 5
num_intervals = 30
delta = 5
threshold = 0.1

[simulation]
num_nodes = 20
latent_dim = 5
num_segments = 3
num_samples_per_segment = 50
