[run]  
dataset = "simulation"  

[parameters]  
latent_dim = 70  
num_intervals = 90  
delta = 5  
threshold = 'none'  

[simulation]  
num_nodes = 70  
latent_dim = 70  
num_segments = 3  
num_samples_per_segment = 50  
